import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const files = [
  ["index.html", "text/html; charset=utf-8"],
  ["styles.css", "text/css; charset=utf-8"],
  ["app.js", "text/javascript; charset=utf-8"],
  ["data/dashboard.json", "application/json; charset=utf-8"],
  ["data/general_pool_analysis.json", "application/json; charset=utf-8"],
  ["data/sector_flow_review.json", "application/json; charset=utf-8"],
  ["data/sector_rotation_intelligence.json", "application/json; charset=utf-8"],
  ["data/sector_rotation_history.json", "application/json; charset=utf-8"],
  ["data/sector_module_review.json", "application/json; charset=utf-8"],
  ["data/etf_decision_readiness.json", "application/json; charset=utf-8"],
  ["data/data_reality_audit.json", "application/json; charset=utf-8"],
  ["data/daily_sector_analysis.json", "application/json; charset=utf-8"],
  ["data/module_maturity_audit.json", "application/json; charset=utf-8"],
  ["data/etf_flow_leaderboard.json", "application/json; charset=utf-8"],
  ["data/sector_signal_attribution.json", "application/json; charset=utf-8"],
  ["data/sector_watchlist_state.json", "application/json; charset=utf-8"],
  ["data/decision_gate_ledger.json", "application/json; charset=utf-8"],
  ["data/index_explainability.json", "application/json; charset=utf-8"],
  ["data/observation_snapshot.json", "application/json; charset=utf-8"],
  ["data/manual_review_log.json", "application/json; charset=utf-8"],
  ["data/outcome_labels.json", "application/json; charset=utf-8"],
  ["data/daily_data_vault.json", "application/json; charset=utf-8"],
  ["data/flow_channel_report.json", "application/json; charset=utf-8"],
  ["data/pool_flow_signals.json", "application/json; charset=utf-8"],
  ["data/market_signal_report.json", "application/json; charset=utf-8"],
  ["data/pool_market_signals.json", "application/json; charset=utf-8"],
  ["data/pool_instrument_map.json", "application/json; charset=utf-8"],
  ["data/pool_mapping_report.json", "application/json; charset=utf-8"],
  ["data/signal_quality_report.json", "application/json; charset=utf-8"],
  ["data/pool_signal_quality.json", "application/json; charset=utf-8"],
  ["data/evening_observation_summary.json", "application/json; charset=utf-8"],
  ["data/pool_observation_scores.json", "application/json; charset=utf-8"],
  ["data/evening_report.md", "text/markdown; charset=utf-8"],
  ["data/observation_candidate_ledger.json", "application/json; charset=utf-8"],
  ["data/score_calibration_report.json", "application/json; charset=utf-8"],
  ["data/candidate_review_schedule.json", "application/json; charset=utf-8"],
  ["data/candidate_outcome_reviews.json", "application/json; charset=utf-8"],
  ["data/outcome_review_report.json", "application/json; charset=utf-8"],
  ["data/data_coverage_report.json", "application/json; charset=utf-8"],
  ["data/coverage_history.json", "application/json; charset=utf-8"],
  ["data/history/latest_observation_pointer.json", "application/json; charset=utf-8"],
  ["data/daily_delta_report.json", "application/json; charset=utf-8"],
  ["data/pool_delta_signals.json", "application/json; charset=utf-8"],
  ["data/daily_delta_history.json", "application/json; charset=utf-8"],
  ["data/news_review.json", "application/json; charset=utf-8"],
  ["data/pond_map.json", "application/json; charset=utf-8"],
];

try {
  const pointer = JSON.parse(await readFile(resolve(root, "financial-pond", "data", "history", "latest_observation_pointer.json"), "utf8"));
  const archiveKey = String(pointer.latest_path ?? "").replace(/^financial-pond\//, "");
  if (archiveKey) files.push([archiveKey, "application/json; charset=utf-8"]);
} catch {
  // Archive assets are added after the daily persistence step has written the pointer.
}

const assets = {};
for (const [file, contentType] of files) {
  assets[file] = {
    content_type: contentType,
    body: await readFile(resolve(root, "financial-pond", file), "utf8"),
  };
}

await writeFile(
  resolve(root, "worker/assets.js"),
  `// Generated by scripts/build-assets.mjs
export const ASSETS = ${JSON.stringify(assets)};
`
);

console.log(`Embedded ${files.length} Financial Ponds assets`);
