import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const files = [
  ["index.html", "text/html; charset=utf-8"],
  ["styles.css", "text/css; charset=utf-8"],
  ["app.js", "text/javascript; charset=utf-8"],
  ["data/dashboard.json", "application/json; charset=utf-8"],
  ["data/sector_flow_review.json", "application/json; charset=utf-8"],
  ["data/news_review.json", "application/json; charset=utf-8"],
  ["data/pond_map.json", "application/json; charset=utf-8"],
];

const assets = {};
for (const [file, contentType] of files) {
  assets[file] = {
    content_type: contentType,
    body: await readFile(resolve(root, "financial-pond", file), "utf8"),
  };
}

await writeFile(
  resolve(root, "worker/assets.js"),
  `// Generated by scripts/build-assets.mjs
export const ASSETS = ${JSON.stringify(assets)};
`
);

console.log(`Embedded ${files.length} Financial Ponds assets`);
